export interface FallbackProduct {
  id: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  unit: string;
  image_url: string;
  is_featured: boolean;
  status?: string;
  category_id?: string;
  formats?: { name: string; price: number }[];
}

export interface FallbackCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  image_url: string;
}

export const FALLBACK_CATEGORIES: FallbackCategory[] = [
  {
    id: 'cat-viandes',
    name: 'Viandes',
    slug: 'viandes',
    description: 'Sélection de viandes fraîches et de qualité supérieure (bœuf, mouton, cabri, pintade).',
    image_url: '/images-rayon/nos-viandes.jpg',
  },
  {
    id: 'cat-epices',
    name: 'Épices',
    slug: 'epices',
    description: 'Épices naturelles et aromates locaux moulus ou entiers pour sublimer vos plats.',
    image_url: '/images-rayon/nos-epices.jpg',
  },
  {
    id: 'cat-farines',
    name: 'Farines',
    slug: 'farines',
    description: 'Farines locales béninoises riches en nutriments pour vos bouillies, pâtes et pâtisseries.',
    image_url: '/images-rayon/nos-farines.jpg',
  },
  {
    id: 'cat-transformes',
    name: 'Produits Transformés',
    slug: 'transformes',
    description: 'Produits agroalimentaires locaux transformés avec soin (huiles, pâte d\'arachide, miel).',
    image_url: '/images-rayon/produits-transformes.jpg',
  },
];

export const FALLBACK_PRODUCTS: Record<string, FallbackProduct[]> = {
  viandes: [
    {
      id: 'v-boeuf',
      name: 'Viande de Bœuf',
      slug: 'viande-de-boeuf',
      description: 'Viande de bœuf fraîche, découpée selon vos préférences (avec ou sans os). Issue d\'élevages locaux sains.',
      price: 4000,
      unit: 'kg',
      image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
      is_featured: true,
    },
    {
      id: 'v-mouton',
      name: 'Viande de Mouton',
      slug: 'viande-de-mouton',
      description: 'Viande de mouton tendre et savoureuse pour vos ragoûts et grillades.',
      price: 4500,
      unit: 'kg',
      image_url: '/images-articles/viande-de-mouton.png',
      is_featured: true,
    },
    {
      id: 'v-cabri',
      name: 'Viande de Cabri',
      slug: 'viande-de-cabri',
      description: 'Viande de cabri fraîche de qualité supérieure, idéale pour les sauces locales.',
      price: 5000,
      unit: 'kg',
      image_url: 'https://images.unsplash.com/photo-1524450373400-58079f298816?auto=format&fit=crop&q=80&w=600',
      is_featured: false,
    },
    {
      id: 'v-poulet',
      name: 'Poulet Bicyclette',
      slug: 'poulet-bicyclette',
      description: 'Poulet local béninois élevé en plein air. Chair ferme et savoureuse (prix indicatif 4000 - 4500 FCFA selon taille).',
      price: 4000,
      unit: 'pièce',
      image_url: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&q=80&w=600',
      is_featured: true,
    },
    {
      id: 'v-pintade',
      name: 'Pintade',
      slug: 'pintade',
      description: 'Pintade locale fraîche, nettoyée et prête à la cuisson. Idéale pour les fêtes.',
      price: 5500,
      unit: 'pièce',
      image_url: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&q=80&w=600',
      is_featured: false,
    },
    {
      id: 'v-blokoto',
      name: 'Blokoto (Pied de bœuf)',
      slug: 'blokoto',
      description: 'Pied de bœuf découpé en morceaux, parfait pour préparer la fameuse sauce Blokoto traditionnelle.',
      price: 3500,
      unit: 'lot',
      image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
      is_featured: false,
    },
    {
      id: 'v-hachee',
      name: 'Viande Hachée',
      slug: 'viande-hachee',
      description: 'Viande de bœuf pure fraîchement hachée, sans additifs.',
      price: 4000,
      unit: 'kg',
      image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=600',
      is_featured: false,
    },
  ],
  epices: [
    {
      id: 'e-curcuma',
      name: 'Curcuma',
      slug: 'curcuma',
      description: 'Curcuma local pur séché et réduit en poudre, excellent antioxydant.',
      price: 1000,
      unit: 'format',
      image_url: '/images-articles/curcuma.png',
      is_featured: true,
      formats: [
        { name: '250g', price: 1000 },
        { name: '500g', price: 1800 },
        { name: '1kg', price: 3500 },
      ],
    },
    {
      id: 'e-poivre-noir',
      name: 'Poivre Noir',
      slug: 'poivre-noir',
      description: 'Poivre noir moulu de première qualité, arôme intense.',
      price: 1000,
      unit: 'format',
      image_url: '/images-articles/poivre-noir.jpg',
      is_featured: true,
      formats: [
        { name: '250g', price: 1000 },
        { name: '500g', price: 1800 },
      ],
    },
    {
      id: 'e-poivre-blanc',
      name: 'Poivre Blanc',
      slug: 'poivre-blanc',
      description: 'Poivre blanc raffiné en poudre pour vos sauces blanches et grillades.',
      price: 2500,
      unit: 'format',
      image_url: '/images-articles/poivre-blanc.jpg',
      is_featured: false,
      formats: [
        { name: '250g', price: 2500 },
        { name: '500g', price: 4800 },
      ],
    },
    {
      id: 'e-clou-girofle',
      name: 'Clou de Girofle',
      slug: 'clou-de-girofle',
      description: 'Clous de girofle entiers ou moulus pour parfumer vos thés, bouillies et plats.',
      price: 1000,
      unit: 'format',
      image_url: 'https://images.unsplash.com/photo-1609144883398-356a6552a4ea?auto=format&fit=crop&q=80&w=600',
      is_featured: false,
      formats: [
        { name: '250g', price: 1000 },
        { name: '500g', price: 1800 },
      ],
    },
    {
      id: 'e-romarin',
      name: 'Romarin sec',
      slug: 'romarin',
      description: 'Herbes de romarin séchées, idéales pour assaisonner les viandes rôties.',
      price: 1000,
      unit: 'format',
      image_url: '/images-articles/romarin.jpg',
      is_featured: false,
      formats: [
        { name: '250g', price: 1000 },
        { name: '500g', price: 1800 },
      ],
    },
    {
      id: 'e-thym',
      name: 'Thym',
      slug: 'thym',
      description: 'Thym séché sélectionné, parfait pour vos marinades.',
      price: 1000,
      unit: 'format',
      image_url: '/images-articles/thym.jpg',
      is_featured: false,
      formats: [
        { name: '250g', price: 1000 },
        { name: '500g', price: 1800 },
      ],
    },
    {
      id: 'e-provence',
      name: 'Herbes de Provence',
      slug: 'herbes-de-provence',
      description: 'Mélange traditionnel d\'herbes séchées pour toutes vos grillades.',
      price: 1000,
      unit: 'format',
      image_url: '/images-articles/herbes-de-provence.jpg',
      is_featured: false,
      formats: [
        { name: '250g', price: 1000 },
        { name: '500g', price: 1800 },
      ],
    },
    {
      id: 'e-piment-poudre',
      name: 'Piment en Poudre',
      slug: 'piment-en-poudre',
      description: 'Piment rouge local piquant moulu, pour relever vos plats.',
      price: 1000,
      unit: 'format',
      image_url: '/images-articles/piment-en-poudre.jpg',
      is_featured: true,
      formats: [
        { name: '250g', price: 1000 },
        { name: '500g', price: 1800 },
      ],
    },
    {
      id: 'e-cumin',
      name: 'Cumin',
      slug: 'cumin',
      description: 'Cumin moulu au parfum chaud et épicé.',
      price: 1600,
      unit: 'format',
      image_url: '/images-articles/cumin.jpg',
      is_featured: false,
      formats: [
        { name: '250g', price: 1600 },
        { name: '500g', price: 3000 },
      ],
    },
    {
      id: 'e-kouka',
      name: 'Kouka',
      slug: 'kouka',
      description: 'Épice traditionnelle locale réputée pour ses vertus et sa saveur unique.',
      price: 1000,
      unit: 'format',
      image_url: '/images-articles/kouka.jpg',
      is_featured: false,
      formats: [
        { name: '250g', price: 1000 },
        { name: '500g', price: 1800 },
      ],
    },
    {
      id: 'e-goussi',
      name: 'Goussi',
      slug: 'goussi',
      description: 'Goussi moulu (pépites de courge) de qualité supérieure pour sauce Egoussi.',
      price: 1000,
      unit: 'format',
      image_url: '/images-articles/goussi.jpg',
      is_featured: false,
      formats: [
        { name: '250g', price: 1000 },
        { name: '500g', price: 1800 },
      ],
    },
    {
      id: 'e-gorona',
      name: 'Gorona',
      slug: 'gorona',
      description: 'Épice locale traditionnelle pour parfumer et relever les sauces.',
      price: 1000,
      unit: 'format',
      image_url: '/images-articles/gorona.jpg',
      is_featured: false,
      formats: [
        { name: '250g', price: 1000 },
        { name: '500g', price: 1800 },
      ],
    },
    {
      id: 'e-asrokouin',
      name: 'Asrokouin',
      slug: 'asrokouin',
      description: 'Poivre de Selim traditionnel, idéal pour les sauces et bouillies.',
      price: 1000,
      unit: 'format',
      image_url: '/warriorsmarket.jpg',
      is_featured: false,
      formats: [
        { name: '250g', price: 1000 },
        { name: '500g', price: 1800 },
      ],
    },
    {
      id: 'e-fretin',
      name: 'Frétin en Poudre',
      slug: 'fretin',
      description: 'Petits poissons séchés et moulus en poudre pour rehausser le goût de vos sauces.',
      price: 1500,
      unit: 'format',
      image_url: '/images-articles/fretin.jpg',
      is_featured: false,
      formats: [
        { name: '250g', price: 1500 },
        { name: '500g', price: 2800 },
      ],
    },
  ],
  farines: [
    {
      id: 'f-telibo',
      name: 'Farine de Télibo',
      slug: 'farine-de-telibo',
      description: 'Farine d\'igname de qualité supérieure pour la préparation de l\'Amala / Télibo traditionnel.',
      price: 750,
      unit: 'format',
      image_url: '/images-articles/farine-de-telibo.jpg',
      is_featured: true,
      formats: [
        { name: '500g', price: 750 },
        { name: '1kg', price: 1500 },
      ],
    },
    {
      id: 'f-soja',
      name: 'Farine de Soja',
      slug: 'farine-de-soja',
      description: 'Farine de soja grillé, riche en protéines, parfaite pour fortifier les bouillies.',
      price: 750,
      unit: 'format',
      image_url: '/images-articles/farine-de-soja.jpg',
      is_featured: true,
      formats: [
        { name: '500g', price: 750 },
        { name: '1kg', price: 1500 },
      ],
    },
    {
      id: 'f-mil',
      name: 'Farine de Mil',
      slug: 'farine-de-mil',
      description: 'Farine de mil pur, idéale pour la préparation de bouillies nutritives traditionnelles.',
      price: 500,
      unit: 'format',
      image_url: 'https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?auto=format&fit=crop&q=80&w=600',
      is_featured: false,
      formats: [
        { name: '500g', price: 500 },
        { name: '1kg', price: 1000 },
      ],
    },
    {
      id: 'f-sorgho',
      name: 'Farine de Sorgho',
      slug: 'farine-de-sorgho',
      description: 'Farine de sorgho rouge riche en fer et nutriments, excellente pour la santé.',
      price: 500,
      unit: 'format',
      image_url: '/images-articles/farine-de-sorgho.jpg',
      is_featured: false,
      formats: [
        { name: '500g', price: 500 },
        { name: '1kg', price: 1000 },
      ],
    },
    {
      id: 'f-baobab',
      name: 'Farine de Baobab',
      slug: 'farine-de-baobab',
      description: 'Poudre de pulpe de fruit de Baobab (Pain de singe), riche en vitamine C et fibres.',
      price: 2500,
      unit: 'format',
      image_url: 'https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?auto=format&fit=crop&q=80&w=600',
      is_featured: true,
      formats: [
        { name: '500g', price: 2500 },
        { name: '1kg', price: 4500 },
      ],
    },
    {
      id: 'f-mais',
      name: 'Farine de Maïs',
      slug: 'farine-de-mais',
      description: 'Farine de maïs blanc ou jaune sélectionné pour la pâte et les bouillies.',
      price: 700,
      unit: 'format',
      image_url: 'https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?auto=format&fit=crop&q=80&w=600',
      is_featured: false,
      formats: [
        { name: '500g', price: 700 },
        { name: '1kg', price: 1200 },
      ],
    },
  ],
  transformes: [
    {
      id: 't-arachide',
      name: 'Pâte d\'arachide',
      slug: 'pate-d-arachide',
      description: 'Pâte d\'arachide crémeuse et 100% naturelle, sans additifs ni huiles ajoutées. Idéale pour les sauces.',
      price: 500,
      unit: 'format',
      image_url: '/images-articles/pate-d-arachide.png',
      is_featured: true,
      formats: [
        { name: '250g', price: 500 },
        { name: '500g', price: 1500 },
      ],
    },
    {
      id: 't-huile',
      name: 'Huile d\'arachide',
      slug: 'huile-d-arachide',
      description: 'Huile d\'arachide pure extraite localement de manière artisanale et saine.',
      price: 1000,
      unit: 'format',
      image_url: '/images-articles/huile-d-arachide.jpg',
      is_featured: true,
      formats: [
        { name: '500ml', price: 1000 },
        { name: '1L', price: 2000 },
      ],
    },
    {
      id: 't-miel',
      name: 'Miel',
      slug: 'miel-naturel',
      description: 'Miel sauvage 100% pur récolté dans les forêts béninoises. Qualité garantie sans sucre ajouté.',
      price: 2000,
      unit: 'format',
      image_url: '/images-articles/miel.png',
      is_featured: true,
      formats: [
        { name: '500ml', price: 2000 },
        { name: '1L', price: 4000 },
      ],
    },
    {
      id: 't-karite',
      name: 'Beurre de Karité',
      slug: 'beurre-de-karite',
      description: 'Beurre de karité brut pur, extrait dans le nord du Bénin. Idéal pour l\'usage alimentaire et cosmétique.',
      price: 500,
      unit: 'format',
      image_url: '/images-articles/beurre-de-karite.jpg',
      is_featured: false,
      formats: [
        { name: '250g', price: 500 },
        { name: '500g', price: 1000 },
      ],
    },
    {
      id: 't-koulikouli',
      name: 'Koulikouli',
      slug: 'koulikouli',
      description: 'Koulikouli croquant traditionnel préparé avec de la pâte d\'arachide épicée.',
      price: 2000,
      unit: 'sachet',
      image_url: '/images-articles/koulikouli.jpg',
      is_featured: true,
    },
  ],
};

export const ALL_PRODUCTS: FallbackProduct[] = Object.values(FALLBACK_PRODUCTS).flat();
export const FEATURED_PRODUCTS: FallbackProduct[] = ALL_PRODUCTS.filter(p => p.is_featured);
